Insert into Player_records value(1,'SC Ganguly','8-Jul-72','Left_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(2,'BB McCullum','27-Sep-81','Right_Hand','Right-arm medium','New Zealand',0,NA);
Insert into Player_records value(3,'RT Ponting','19-Dec-74','Right_Hand','Right-arm medium','Australia',0,NA);
Insert into Player_records value(4,'DJ Hussey','15-Jul-77','Right_Hand','Right-arm offbreak','Australia',0,NA);
Insert into Player_records value(5,'Mohammad Hafeez','17-Oct-80','Right_Hand','Right-arm offbreak','Pakistan',0,NA);
Insert into Player_records value(6,'R Dravid','11-Jan-73','Right_Hand','Right-arm offbreak','India',0,NA);
Insert into Player_records value(7,'W Jaffer','16-Feb-78','Right_Hand','Right-arm offbreak','India',0,NA);
Insert into Player_records value(8,'V Kohli','5-Nov-88','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(9,'JH Kallis','16-Oct-75','Right_Hand','Right-arm fast-medium','South Africa',0,NA);
Insert into Player_records value(10,'CL White','18-Aug-83','Right_Hand','Legbreak googly','Australia',0,NA);
Insert into Player_records value(11,'MV Boucher','3-Dec-76','Right_Hand','Right-arm medium','South Africa',0,NA);
Insert into Player_records value(12,'B Akhil','7-Oct-77','Right_Hand','Right-arm medium-fast','India',0,NA);
Insert into Player_records value(13,'AA Noffke','30-Apr-77','Right_Hand','Right-arm fast-medium','Australia',0,NA);
Insert into Player_records value(14,'P Kumar','2-Oct-86','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(15,'Z Khan','7-Oct-78','Right_Hand','Left-arm fast-medium','India',0,NA);
Insert into Player_records value(16,'SB Joshi','6-Jun-70','Left_Hand','Slow left-arm orthodox','India',0,NA);
Insert into Player_records value(17,'PA Patel','9-Mar-85','Left_Hand','NULL','India',0,NA);
Insert into Player_records value(18,'ML Hayden','29-Oct-71','Left_Hand','Right-arm medium','Australia',0,NA);
Insert into Player_records value(19,'MEK Hussey','27-May-75','Left_Hand','Right-arm medium','Australia',0,NA);
Insert into Player_records value(20,'MS Dhoni','7-Jul-81','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(21,'SK Raina','27-Nov-86','Left_Hand','Right-arm offbreak','India',0,NA);
Insert into Player_records value(22,'JDP Oram','28-Jul-78','Left_Hand','Right-arm fast-medium','New Zealand',0,NA);
Insert into Player_records value(23,'S Badrinath','30-Aug-80','Right_Hand','Right-arm offbreak','India',0,NA);
Insert into Player_records value(24,'K Goel','24-Dec-86','Left_Hand','Right-arm offbreak','India',0,NA);
Insert into Player_records value(25,'JR Hopes','24-Oct-78','Right_Hand','Right-arm medium','Australia',0,NA);
Insert into Player_records value(26,'KC Sangakkara','27-Oct-77','Left_Hand','Right-arm offbreak','Sri Lanka',0,NA);
Insert into Player_records value(27,'Yuvraj Singh','12-Dec-81','Left_Hand','Slow left-arm orthodox','India',0,NA);
Insert into Player_records value(28,'SM Katich','21-Aug-75','Left_Hand','Slow left-arm chinaman','Australia',0,NA);
Insert into Player_records value(29,'IK Pathan','27-Oct-84','Left_Hand','Left-arm medium-fast','India',0,NA);
Insert into Player_records value(30,'T Kohli','17-Dec-88','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(31,'YK Pathan','17-Nov-82','Right_Hand','Right-arm offbreak','India',0,NA);
Insert into Player_records value(32,'SR Watson','17-Jun-81','Right_Hand','Right-arm fast-medium','Australia',0,NA);
Insert into Player_records value(33,'M Kaif','1-Dec-80','Right_Hand','Right-arm offbreak','India',0,NA);
Insert into Player_records value(34,'DS Lehmann','5-Feb-70','Left_Hand','Slow left-arm orthodox','Australia',0,NA);
Insert into Player_records value(35,'RA Jadeja','6-Dec-88','Left_Hand','Slow left-arm orthodox','India',0,NA);
Insert into Player_records value(36,'M Rawat','25-Oct-85','Right_Hand','NULL','India',0,NA);
Insert into Player_records value(37,'D Salunkhe','12-Nov-82','Right_Hand','Legbreak','India',0,NA);
Insert into Player_records value(38,'SK Warne','13-Sep-69','Right_Hand','Legbreak googly','Australia',0,NA);
Insert into Player_records value(39,'SK Trivedi','4-Sep-82','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(40,'G Gambhir','14-Oct-81','Left_Hand','Legbreak','India',0,NA);
Insert into Player_records value(41,'V Sehwag','20-Oct-78','Right_Hand','Right-arm offbreak','India',0,NA);
Insert into Player_records value(42,'S Dhawan','5-Dec-85','Left_Hand','Right-arm offbreak','India',0,NA);
Insert into Player_records value(43,'L Ronchi','23-Apr-81','Right_Hand','NULL','Australia',0,NA);
Insert into Player_records value(44,'ST Jayasuriya','30-Jun-69','Left_Hand','Slow left-arm orthodox','Sri Lanka',0,NA);
Insert into Player_records value(45,'DJ Thornely','1-Oct-78','Right_Hand','Right-arm medium','Australia',0,NA);
Insert into Player_records value(46,'RV Uthappa','11-Nov-85','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(47,'PR Shah','3-Nov-87','Right_Hand','NULL','India',0,NA);
Insert into Player_records value(48,'AM Nayar','8-Oct-83','Left_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(49,'SM Pollock','16-Jul-73','Right_Hand','Right-arm fast-medium','South Africa',0,NA);
Insert into Player_records value(50,'Harbhajan Singh','3-Jul-80','Right_Hand','Right-arm offbreak','India',0,NA);
Insert into Player_records value(51,'S Chanderpaul','16-Aug-74','Left_Hand','Legbreak','West Indies',0,NA);
Insert into Player_records value(52,'LRPL Taylor','8-Mar-84','Right_Hand','Right-arm offbreak','New Zealand',0,NA);
Insert into Player_records value(53,'AC Gilchrist','14-Nov-71','Left_Hand','Right-arm offbreak','Australia',0,NA);
Insert into Player_records value(54,'Y Venugopal Rao','26-Feb-82','Right_Hand','Right-arm offbreak','India',0,NA);
Insert into Player_records value(55,'VVS Laxman','1-Nov-74','Right_Hand','Right-arm offbreak','India',0,NA);
Insert into Player_records value(56,'A Symonds','9-Jun-75','Right_Hand','Right-arm offbreak','Australia',0,NA);
Insert into Player_records value(57,'RG Sharma','30-Apr-87','Right_Hand','Right-arm offbreak','India',0,NA);
Insert into Player_records value(58,'SB Styris','10-Jul-75','Right_Hand','Right-arm medium','New Zealand',0,NA);
Insert into Player_records value(59,'SB Bangar','11-Oct-72','Right_Hand','Right-arm medium-fast','India',0,NA);
Insert into Player_records value(60,'WPUJC Vaas','27-Jan-74','Left_Hand','Left-arm fast-medium','Sri Lanka',0,NA);
Insert into Player_records value(61,'RP Singh','6-Dec-85','Right_Hand','Left-arm fast-medium','India',0,NA);
Insert into Player_records value(62,'WP Saha','24-Oct-84','Right_Hand','NULL','India',0,NA);
Insert into Player_records value(63,'LR Shukla','6-May-81','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(64,'DPMD Jayawardene','27-May-77','Right_Hand','Right-arm medium','Sri Lanka',0,NA);
Insert into Player_records value(65,'S Sohal','10-Nov-87','Right_Hand','Legbreak','India',0,NA);
Insert into Player_records value(66,'B Lee','8-Nov-76','Right_Hand','Right-arm fast','Australia',0,NA);
Insert into Player_records value(67,'PP Chawla','24-Dec-88','Left_Hand','Legbreak','India',0,NA);
Insert into Player_records value(68,'WA Mota','20-Sep-81','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(69,'Kamran Akmal','13-Jan-82','Right_Hand','NULL','Pakistan',0,NA);
Insert into Player_records value(70,'Shahid Afridi','1-Mar-80','Right_Hand','Legbreak googly','Pakistan',0,NA);
Insert into Player_records value(71,'DJ Bravo','7-Oct-83','Right_Hand','Right-arm medium-fast','West Indies',0,NA);
Insert into Player_records value(72,'MA Khote','22-Apr-80','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(73,'A Nehra','29-Apr-79','Right_Hand','Left-arm medium-fast','India',0,NA);
Insert into Player_records value(74,'GC Smith','1-Feb-81','Left_Hand','Right-arm offbreak','South Africa',0,NA);
Insert into Player_records value(75,'Pankaj Singh','6-May-85','Right_Hand','Right-arm medium-fast','India',0,NA);
Insert into Player_records value(76,'RR Sarwan','23-Jun-80','Right_Hand','Legbreak','West Indies',0,NA);
Insert into Player_records value(77,'S Sreesanth','6-Feb-83','Right_Hand','Right-arm fast-medium','India',0,NA);
Insert into Player_records value(78,'VRV Singh','17-Sep-84','Right_Hand','Right-arm medium-fast','India',0,NA);
Insert into Player_records value(79,'SS Tiwary','30-Dec-89','Left_Hand','NULL','India',0,NA);
Insert into Player_records value(80,'DS Kulkarni','10-Dec-88','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(81,'R Vinay Kumar','12-Feb-84','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(82,'AB Agarkar','4-Dec-77','Right_Hand','Right-arm fast','India',0,NA);
Insert into Player_records value(83,'M Kartik','11-Sep-76','Left_Hand','Slow left-arm orthodox','India',0,NA);
Insert into Player_records value(84,'I Sharma','2-Sep-88','Right_Hand','Right-arm fast-medium','India',0,NA);
Insert into Player_records value(85,'AM Rahane','6-Jun-88','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(86,'Shoaib Malik','1-Feb-82','Right_Hand','Right-arm offbreak','Pakistan',0,NA);
Insert into Player_records value(87,'MK Tiwary','14-Nov-85','Right_Hand','Legbreak googly','India',0,NA);
Insert into Player_records value(88,'KD Karthik','1-Jun-85','Right_Hand','NULL','India',0,NA);
Insert into Player_records value(89,'R Bhatia','22-Oct-79','Right_Hand','Right-arm medium-fast','India',0,NA);
Insert into Player_records value(90,'MF Maharoof','7-Sep-84','Right_Hand','Right-arm fast-medium','India',0,NA);
Insert into Player_records value(91,'VY Mahesh','21-Dec-87','Right_Hand','Right-arm medium-fast','India',0,NA);
Insert into Player_records value(92,'TM Srivastava','7-Nov-89','Left_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(93,'B Chipli','27-Jan-83','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(94,'DW Steyn','27-Jun-83','Right_Hand','Right-arm fast','South Africa',0,NA);
Insert into Player_records value(95,'DB Das','22-Sep-86','Right_Hand','Legbreak googly','India',0,NA);
Insert into Player_records value(96,'MK Pandey','10-Sep-89','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(97,'HH Gibbs','23-Feb-74','Right_Hand','Right-arm bowler','South Africa',0,NA);
Insert into Player_records value(98,'DNT Zoysa','13-May-78','Left_Hand','Left-arm fast-medium','Sri Lanka',0,NA);
Insert into Player_records value(99,'D Kalyankrishna','16-Dec-83','Right_Hand','Right-arm medium-fast','India',0,NA);
Insert into Player_records value(100,'SE Marsh','9-Jul-83','Left_Hand','Slow left-arm orthodox','Australia',0,NA);
Insert into Player_records value(101,'SA Asnodkar','29-Mar-84','Right_Hand','Right-arm offbreak','India',0,NA);
Insert into Player_records value(102,'Sohail Tanvir','12-Dec-84','Left_Hand','Left-arm medium-fast','Pakistan',0,NA);
Insert into Player_records value(103,'Salman Butt','7-Oct-84','Left_Hand','Right-arm offbreak','Pakistan',0,NA);
Insert into Player_records value(104,'BJ Hodge','29-Dec-74','Right_Hand','Right-arm offbreak','Australia',0,NA);
Insert into Player_records value(105,'Umar Gul','14-Apr-84','Right_Hand','Right-arm fast-medium','Pakistan',0,NA);
Insert into Player_records value(106,'AB Dinda','25-Mar-84','Right_Hand','Right-arm medium-fast','India',0,NA);
Insert into Player_records value(107,'SP Fleming','1-Apr-73','Left_Hand','NULL','New Zealand',0,NA);
Insert into Player_records value(108,'S Vidyut','3-Dec-81','Left_Hand','Slow left-arm orthodox','India',0,NA);
Insert into Player_records value(109,'JA Morkel','10-Jun-81','Left_Hand','Right-arm medium-fast','South Africa',0,NA);
Insert into Player_records value(110,'AB de Villiers','17-Feb-84','Right_Hand','Right-arm medium','South Africa',0,NA);
Insert into Player_records value(111,'LPC Silva','14-Dec-79','Right_Hand','Legbreak','Sri Lanka',0,NA);
Insert into Player_records value(112,'DB Ravi Teja','5-Sep-87','Right_Hand','Legbreak googly','India',0,NA);
Insert into Player_records value(113,'Misbah-ul-Haq','28-May-74','Right_Hand','Legbreak','Pakistan',0,NA);
Insert into Player_records value(114,'YV Takawale','5-Nov-84','Right_Hand','NULL','India',0,NA);
Insert into Player_records value(115,'RR Raje','3-Sep-86','Right_Hand','Right-arm fast-medium','India',0,NA);
Insert into Player_records value(116,'PJ Sangwan','5-Nov-90','Right_Hand','Left-arm medium','India',0,NA);
Insert into Player_records value(117,'Mohammad Asif','20-Dec-82','Left_Hand','Right-arm fast-medium','Pakistan',0,NA);
Insert into Player_records value(118,'GD McGrath','9-Feb-70','Right_Hand','Right-arm fast-medium','Australia',0,NA);
Insert into Player_records value(119,'Joginder Sharma','23-Oct-83','Right_Hand','Right-arm fast-medium','India',0,NA);
Insert into Player_records value(120,'MS Gony','4-Jan-84','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(121,'M Muralitharan','17-Apr-72','Right_Hand','Right-arm offbreak','Sri Lanka',0,NA);
Insert into Player_records value(122,'M Ntini','6-Jul-77','Right_Hand','Right-arm fast','South Africa',0,NA);
Insert into Player_records value(123,'DT Patil','6-Dec-84','Right_Hand','NULL','India',0,NA);
Insert into Player_records value(124,'A Kumble','17-Oct-70','Right_Hand','Legbreak googly','India',0,NA);
Insert into Player_records value(125,'S Anirudha','14-Apr-87','Right_Hand','NULL','India',0,NA);
Insert into Player_records value(126,'MM Patel','12-Jul-83','Right_Hand','Right-arm medium-fast','India',0,NA);
Insert into Player_records value(127,'CK Kapugedera','24-Feb-87','Right_Hand','Right-arm medium','Sri Lanka',0,NA);
Insert into Player_records value(128,'A Chopra','19-Sep-77','Right_Hand','Right-arm offbreak','India',0,NA);
Insert into Player_records value(129,'T Taibu','14-May-83','Right_Hand','Right-arm medium','Zimbabwea',0,NA);
Insert into Player_records value(130,'J Arunkumar','18-Jan-75','Right_Hand','Right-arm offbreak','India',0,NA);
Insert into Player_records value(131,'PP Ojha','5-Sep-86','Left_Hand','Slow left-arm orthodox','India',0,NA);
Insert into Player_records value(132,'SP Goswami','18-May-89','Left_Hand','NULL','India',0,NA);
Insert into Player_records value(133,'SR Tendulkar','24-Apr-73','Right_Hand','Right-arm offbreak','India',0,NA);
Insert into Player_records value(134,'U Kaul','2-Dec-87','Left_Hand','NULL','India',0,NA);
Insert into Player_records value(135,'TM Dilshan','14-Oct-76','Right_Hand','Right-arm offbreak','Sri Lanka',0,NA);
Insert into Player_records value(136,'A Mishra','24-Nov-82','Right_Hand','Legbreak','India',0,NA);
Insert into Player_records value(137,'AD Mascarenhas','30-Oct-77','Right_Hand','Right-arm fast-medium','England',0,NA);
Insert into Player_records value(138,'NK Patel','26-Mar-81','Left_Hand','NULL','India',0,NA);
Insert into Player_records value(139,'LA Pomersbach','28-Sep-84','Left_Hand','Right-arm offbreak','Australia',0,NA);
Insert into Player_records value(140,'Iqbal Abdulla','2-Dec-89','Left_Hand','Slow left-arm orthodox','India',0,NA);
Insert into Player_records value(141,'Younis Khan','29-Nov-77','Right_Hand','Right-arm medium','Pakistan',0,NA);
Insert into Player_records value(142,'PM Sarvesh Kumar','26-Apr-89','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(143,'DP Vijaykumar','20-Oct-86','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(144,'Shoaib Akhtar','13-Aug-75','Right_Hand','Right-arm fast','Pakistan',0,NA);
Insert into Player_records value(145,'Abdur Razzak','15-Jun-82','Left_Hand','Slow left-arm orthodox','Bangladesh',0,NA);
Insert into Player_records value(146,'H Das','10-Dec-86','Right_Hand','NULL','India',0,NA);
Insert into Player_records value(147,'DR Smith','12-Apr-83','Right_Hand','Right-arm medium','West Indies',0,NA);
Insert into Player_records value(148,'SD Chitnis','6-May-87','Right_Hand','Right-arm offbreak','India',0,NA);
Insert into Player_records value(149,'CRD Fernando','19-Jul-79','Right_Hand','Right-arm fast-medium','Sri Lanka',0,NA);
Insert into Player_records value(150,'VS Yeligati','23-Apr-85','Right_Hand','Right-arm offbreak','India',0,NA);
Insert into Player_records value(151,'L Balaji','27-Sep-81','Right_Hand','Right-arm medium-fast','India',0,NA);
Insert into Player_records value(152,'A Mukund','6-Jan-90','Left_Hand','Legbreak googly','India',0,NA);
Insert into Player_records value(153,'RR Powar','20-May-78','Right_Hand','Right-arm offbreak','India',0,NA);
Insert into Player_records value(154,'JP Duminy','14-Apr-84','Left_Hand','Right-arm offbreak','South Africa',0,NA);
Insert into Player_records value(155,'A Flintoff','6-Dec-77','Right_Hand','Right-arm fast-medium','England',0,NA);
Insert into Player_records value(156,'T Thushara','1-Mar-81','Left_Hand','Left-arm fast-medium','Sri Lanka',0,NA);
Insert into Player_records value(157,'JD Ryder','6-Aug-84','Left_Hand','Right-arm medium','New Zealand',0,NA);
Insert into Player_records value(158,'KP Pietersen','27-Jun-80','Right_Hand','Right-arm offbreak','South Africa',0,NA);
Insert into Player_records value(159,'T Henderson','1-Aug-74','Right_Hand','Right-arm fast-medium','South Africa',0,NA);
Insert into Player_records value(160,'Kamran Khan','10-Mar-91','Left_Hand','Left-arm medium-fast','India',0,NA);
Insert into Player_records value(161,'RS Bopara','4-May-85','Right_Hand','Right-arm medium','England',0,NA);
Insert into Player_records value(162,'CH Gayle','21-Sep-79','Left_Hand','Right-arm offbreak','West Indies',0,NA);
Insert into Player_records value(163,'MC Henriques','1-Feb-87','Right_Hand','Right-arm fast-medium','Australia',0,NA);
Insert into Player_records value(164,'R Bishnoi','8-Oct-87','Right_Hand','Right-arm medium-fast','India',0,NA);
Insert into Player_records value(165,'FH Edwards','6-Feb-82','Right_Hand','Right-arm fast','West Indies',0,NA);
Insert into Player_records value(166,'KV Sharma','23-Oct-87','Left_Hand','Legbreak googly','India',0,NA);
Insert into Player_records value(167,'PC Valthaty','7-Dec-83','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(168,'RJ Quiney','20-Aug-82','Left_Hand','Right-arm medium','Australia',0,NA);
Insert into Player_records value(169,'AS Raut','3-Mar-87','Right_Hand','Legbreak googly','India',0,NA);
Insert into Player_records value(170,'Yashpal Singh','27-Nov-81','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(171,'M Manhas','12-Oct-79','Right_Hand','Right-arm offbreak','India',0,NA);
Insert into Player_records value(172,'AA Bilakhia','31-May-86','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(173,'AN Ghosh','19-Oct-86','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(174,'BAW Mendis','11-Mar-85','Right_Hand','Right-arm offbreak','Sri Lanka',0,NA);
Insert into Player_records value(175,'DL Vettori','27-Jan-79','Left_Hand','Slow left-arm orthodox','New Zealand',0,NA);
Insert into Player_records value(176,'MN van Wyk','20-Mar-79','Right_Hand','Slow left-arm orthodox','South Africa',0,NA);
Insert into Player_records value(177,'RE van der Merwe','31-Dec-84','Right_Hand','Slow left-arm orthodox','South Africa',0,NA);
Insert into Player_records value(178,'TL Suman','15-Dec-83','Right_Hand','Right-arm offbreak','India',0,NA);
Insert into Player_records value(179,'Shoaib Ahmed','17-Aug-90','Right_Hand','Right-arm fast-medium','Pakistan',0,NA);
Insert into Player_records value(180,'GR Napier','6-Jan-80','Right_Hand','Right-arm medium','England',0,NA);
Insert into Player_records value(181,'KP Appanna','20-Dec-88','Right_Hand','Slow left-arm orthodox','India',0,NA);
Insert into Player_records value(182,'LA Carseldine','17-Nov-75','Left_Hand','Left-arm medium','Australia',0,NA);
Insert into Player_records value(183,'NV Ojha','20-Jul-83','Right_Hand','NULL','India',0,NA);
Insert into Player_records value(184,'SM Harwood','1-Mar-74','Right_Hand','Right-arm fast-medium','Australia',0,NA);
Insert into Player_records value(185,'M Vijay','1-Apr-84','Right_Hand','Right-arm offbreak','India',0,NA);
Insert into Player_records value(186,'SB Jakati','27-Nov-80','Left_Hand','Slow left-arm orthodox','India',0,NA);
Insert into Player_records value(187,'DA Warner','27-Oct-86','Left_Hand','Legbreak','Australia',0,NA);
Insert into Player_records value(188,'RJ Harris','11-Oct-79','Right_Hand','Right-arm fast','Australia',0,NA);
Insert into Player_records value(189,'D du Preez','8-Nov-81','Right_Hand','Right-arm fast-medium','South Africa',0,NA);
Insert into Player_records value(190,'M Morkel','6-Oct-84','Left_Hand','Right-arm fast','South Africa',0,NA);
Insert into Player_records value(191,'AD Mathews','2-Jun-87','Right_Hand','Right-arm fast-medium','Sri Lanka',0,NA);
Insert into Player_records value(192,'J Botha','2-May-82','Right_Hand','Right-arm offbreak','South Africa',0,NA);
Insert into Player_records value(193,'C Nanda','29-Mar-79','Right_Hand','Legbreak','India',0,NA);
Insert into Player_records value(194,'SL Malinga','28-Aug-83','Right_Hand','Right-arm fast','Sri Lanka',0,NA);
Insert into Player_records value(195,'Mashrafe Mortaza','5-Oct-83','Right_Hand','Right-arm fast-medium','Bangladesh',0,NA);
Insert into Player_records value(196,'A Singh','21-Jun-81','Right_Hand','Right-arm medium-fast','India',0,NA);
Insert into Player_records value(197,'GJ Bailey','7-Sep-82','Right_Hand','Right-arm medium','Australia',0,NA);
Insert into Player_records value(198,'AB McDonald','5-Jun-81','Right_Hand','Right-arm fast-medium','Australia',0,NA);
Insert into Player_records value(199,'Y Nagar','6-Jan-90','Right_Hand','Right-arm offbreak','India',0,NA);
Insert into Player_records value(200,'SS Shaikh','18-Jan-87','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(201,'R Ashwin','17-Sep-86','Right_Hand','Right-arm offbreak','India',0,NA);
Insert into Player_records value(202,'Mohammad Ashraful','7-Jul-84','Right_Hand','Right-arm offbreak','Bangladesh',0,NA);
Insert into Player_records value(203,'CA Pujara','25-Jan-88','Right_Hand','Legbreak','India',0,NA);
Insert into Player_records value(204,'OA Shah','22-Oct-78','Right_Hand','Right-arm offbreak','England',0,NA);
Insert into Player_records value(205,'Anirudh Singh','2-Aug-80','Left_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(206,'Jaskaran Singh','4-Sep-89','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(207,'AP Tare','7-Nov-87','Right_Hand','NULL','India',0,NA);
Insert into Player_records value(208,'AT Rayudu','23-Sep-85','Right_Hand','Right-arm offbreak','India',0,NA);
Insert into Player_records value(209,'R Sathish','14-Jan-81','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(210,'R McLaren','9-Feb-83','Left_Hand','Right-arm medium-fast','South Africa',0,NA);
Insert into Player_records value(211,'AA Jhunjhunwala','1-Dec-82','Right_Hand','Right-arm offbreak','India',0,NA);
Insert into Player_records value(212,'P Dogra','19-Nov-84','Right_Hand','Legbreak','India',0,NA);
Insert into Player_records value(213,'A Uniyal','21-Nov-81','Left_Hand','Left-arm medium','India',0,NA);
Insert into Player_records value(214,'MS Bisla','27-Dec-84','Right_Hand','NULL','India',0,NA);
Insert into Player_records value(215,'YA Abdulla','17-Jan-83','Left_Hand','Left-arm fast-medium','India',0,NA);
Insert into Player_records value(216,'EJG Morgan','10-Sep-86','Left_Hand','Right-arm medium','England',0,NA);
Insert into Player_records value(217,'JM Kemp','2-Oct-77','Right_Hand','Right-arm fast-medium','South Africa',0,NA);
Insert into Player_records value(218,'S Tyagi','17-Sep-87','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(219,'RS Gavaskar','20-Feb-76','Left_Hand','Slow left-arm orthodox','India',0,NA);
Insert into Player_records value(220,'SE Bond','7-Jun-75','Right_Hand','Right-arm fast','New Zealand',0,NA);
Insert into Player_records value(221,'KA Pollard','12-May-87','Right_Hand','Right-arm medium-fast','West Indies',0,NA);
Insert into Player_records value(222,'S Ladda','10-Jul-86','Right_Hand','Legbreak','India',0,NA);
Insert into Player_records value(223,'DP Nannes','16-May-76','Right_Hand','Left-arm fast','Australia',0,NA);
Insert into Player_records value(224,'MJ Lumb','12-Feb-80','Left_Hand','Right-arm medium','England',0,NA);
Insert into Player_records value(225,'DR Martyn','21-Oct-71','Right_Hand','Right-arm medium','Australia',0,NA);
Insert into Player_records value(226,'S Narwal','16-Apr-82','Left_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(227,'AB Barath','14-Apr-90','Right_Hand','Right-arm offbreak','India',0,NA);
Insert into Player_records value(228,'Bipul Sharma','28-Sep-83','Left_Hand','Slow left-arm orthodox','India',0,NA);
Insert into Player_records value(229,'FY Fazal','7-Sep-85','Left_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(230,'AC Voges','4-Oct-79','Right_Hand','Slow left-arm orthodox','Australia',0,NA);
Insert into Player_records value(231,'MD Mishra','9-Feb-84','Right_Hand','Right-arm offbreak','India',0,NA);
Insert into Player_records value(232,'UT Yadav','25-Oct-87','Right_Hand','Right-arm fast-medium','India',0,NA);
Insert into Player_records value(233,'J Theron','24-Jul-85','Right_Hand','Right-arm medium-fast','South Africa',0,NA);
Insert into Player_records value(234,'SJ Srivastava','22-Sep-81','Right_Hand','Left-arm fast-medium','India',0,NA);
Insert into Player_records value(235,'R Sharma','30-Apr-87','Right_Hand','Right-arm offbreak','India',0,NA);
Insert into Player_records value(236,'Mandeep Singh','18-Dec-91','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(237,'KM Jadhav','26-Mar-85','Right_Hand','Right-arm offbreak','India',0,NA);
Insert into Player_records value(238,'SW Tait','22-Feb-83','Right_Hand','Right-arm fast','Australia',0,NA);
Insert into Player_records value(239,'KB Arun Karthik','15-Feb-86','Right_Hand','Legbreak googly','India',0,NA);
Insert into Player_records value(240,'KAJ Roach','30-Jun-88','Right_Hand','Right-arm fast','West Indies',0,NA);
Insert into Player_records value(241,'PD Collingwood','26-May-76','Right_Hand','Right-arm medium','England',0,NA);
Insert into Player_records value(242,'CK Langeveldt','17-Dec-74','Right_Hand','Right-arm fast-medium','England',0,NA);
Insert into Player_records value(243,'VS Malik','9-May-83','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(244,'A Mithun','25-Oct-89','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(245,'AP Dole','9-Oct-87','Right_Hand','Right-arm medium-fast','India',0,NA);
Insert into Player_records value(246,'AN Ahmed','5-Nov-88','Right_Hand','Right-arm medium-fast','India',0,NA);
Insert into Player_records value(247,'RS Sodhi','18-Oct-80','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(248,'DE Bollinger','24-Jul-81','Left_Hand','Left-arm fast-medium','Australia',0,NA);
Insert into Player_records value(249,'S Sriram','21-Feb-76','Left_Hand','Slow left-arm orthodox','India',0,NA);
Insert into Player_records value(250,'B Sumanth','10-May-88','Right_Hand','Right-arm medium-fast','India',0,NA);
Insert into Player_records value(251,'C Madan','15-Oct-82','Right_Hand','NULL','India',0,NA);
Insert into Player_records value(252,'AG Paunikar','18-Apr-88','Right_Hand','NULL','India',0,NA);
Insert into Player_records value(253,'MR Marsh','20-Oct-91','Right_Hand','Right-arm medium','Australia',0,NA);
Insert into Player_records value(254,'AJ Finch','17-Nov-86','Right_Hand','Slow left-arm orthodox','Australia',0,NA);
Insert into Player_records value(255,'STR Binny','3-Jun-84','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(256,'Harmeet Singh','7-Sep-92','Left_Hand','Slow left-arm orthodox','India',0,NA);
Insert into Player_records value(257,'IR Jaggi','27-Jan-89','Right_Hand','Legbreak googly','India',0,NA);
Insert into Player_records value(258,'DT Christian','4-May-83','Right_Hand','Right-arm fast-medium','Australia',0,NA);
Insert into Player_records value(259,'RV Gomez','16-Oct-85','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(260,'MA Agarwal','16-Feb-91','Right_Hand','NULL','India',0,NA);
Insert into Player_records value(261,'AUK Pathan','17-Jun-84','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(262,'UBT Chand','26-Mar-93','Right_Hand','Right-arm offbreak','India',0,NA);
Insert into Player_records value(263,'DJ Jacobs','4-Nov-82','Right_Hand','Right-arm medium','South Africa',0,NA);
Insert into Player_records value(264,'Sunny Singh','18-Dec-86','Right_Hand','Right-arm medium-fast','India',0,NA);
Insert into Player_records value(265,'NJ Rimmington','11-Nov-82','Right_Hand','Right-arm fast-medium','Australia',0,NA);
Insert into Player_records value(266,'AL Menaria','29-Oct-90','Left_Hand','Slow left-arm orthodox','India',0,NA);
Insert into Player_records value(267,'WD Parnell','30-Jul-89','Left_Hand','Left-arm medium-fast','South Africa',0,NA);
Insert into Player_records value(268,'JJ van der Wath','10-Jan-78','Right_Hand','Right-arm medium-fast','South Africa',0,NA);
Insert into Player_records value(269,'R Ninan','19-Nov-85','Right_Hand','Right-arm offbreak','India',0,NA);
Insert into Player_records value(270,'S Aravind','8-Apr-84','Left_Hand','Left-arm medium-fast','India',0,NA);
Insert into Player_records value(271,'MS Wade','26-Dec-87','Left_Hand','Right-arm medium','Australia',0,NA);
Insert into Player_records value(272,'TD Paine','8-Dec-84','Right_Hand','Right-arm medium','Australia',0,NA);
Insert into Player_records value(273,'SB Wagh','9-Oct-88','Left_Hand','Left-arm medium-fast','India',0,NA);
Insert into Player_records value(274,'AC Thomas','9-Feb-77','Right_Hand','Right-arm fast-medium','England',0,NA);
Insert into Player_records value(275,'JEC Franklin','7-Nov-80','Left_Hand','Left-arm medium','New Zealand',0,NA);
Insert into Player_records value(276,'Shakib Al Hasan','24-Mar-87','Left_Hand','Slow left-arm orthodox','Bangladesh',0,NA);
Insert into Player_records value(277,'DH Yagnik','22-Jun-83','Left_Hand','NULL','India',0,NA);
Insert into Player_records value(278,'S Randiv','30-Jan-85','Right_Hand','Right-arm offbreak','Sri Lanka',0,NA);
Insert into Player_records value(279,'BJ Haddin','23-Oct-77','Right_Hand','NULL','Australia',0,NA);
Insert into Player_records value(280,'NLTC Perera','3-Apr-89','Left_Hand','Right-arm medium-fast','Sri Lanka',0,NA);
Insert into Player_records value(281,'NL McCullum','1-Sep-80','Right_Hand','Right-arm offbreak','New Zealand',0,NA);
Insert into Player_records value(282,'JE Taylor','22-Jun-84','Right_Hand','Right-arm fast','New Zealand',0,NA);
Insert into Player_records value(283,'J Syed Mohammad','3-Jun-83','Left_Hand','Slow left-arm orthodox','India',0,NA);
Insert into Player_records value(284,'RN ten Doeschate','30-Jun-80','Right_Hand','Right-arm medium-fast','Netherlands',0,NA);
Insert into Player_records value(285,'TR Birt','9-Dec-81','Left_Hand','Right-arm medium','Australia',0,NA);
Insert into Player_records value(286,'AG Murtaza','1-Jan-90','Left_Hand','Slow left-arm orthodox','India',0,NA);
Insert into Player_records value(287,'Harpreet Singh','11-Aug-91','Left_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(288,'M Klinger','4-Jul-80','Right_Hand','NULL','Australia',0,NA);
Insert into Player_records value(289,'AC Blizzard','27-Jun-84','Left_Hand','Left-arm medium','Australia',0,NA);
Insert into Player_records value(290,'I Malhotra','23-May-84','Right_Hand','Right-arm medium-fast','India',0,NA);
Insert into Player_records value(291,'L Ablish','3-Dec-82','Right_Hand','Right-arm medium-fast','India',0,NA);
Insert into Player_records value(292,'CA Ingram','3-Jul-85','Left_Hand','Legbreak','South Africa',0,NA);
Insert into Player_records value(293,'S Nadeem','12-Aug-89','Right_Hand','Slow left-arm orthodox','India',0,NA);
Insert into Player_records value(294,'P Parameswaran','30-May-85','Right_Hand','Left-arm medium','India',0,NA);
Insert into Player_records value(295,'CJ Ferguson','21-Nov-84','Right_Hand','Right-arm medium','Australia',0,NA);
Insert into Player_records value(296,'VR Aaron','29-Oct-89','Right_Hand','Right-arm fast','India',0,NA);
Insert into Player_records value(297,'AA Chavan','28-Oct-85','Left_Hand','Slow left-arm orthodox','India',0,NA);
Insert into Player_records value(298,'ND Doshi','6-Oct-78','Right_Hand','Slow left-arm orthodox','India',0,NA);
Insert into Player_records value(299,'B Kumar','5-Feb-90','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(300,'Y Gnaneswara Rao','25-Aug-84','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(301,'S Rana','18-Sep-84','Right_Hand','Right-arm medium-fast','India',0,NA);
Insert into Player_records value(302,'BA Bhatt','13-May-90','Left_Hand','Slow left-arm orthodox','India',0,NA);
Insert into Player_records value(303,'F du Plessis','13-Jul-84','Right_Hand','Legbreak','South Africa',0,NA);
Insert into Player_records value(304,'RE Levi','14-Jan-88','Right_Hand','Right-arm medium','South Africa',0,NA);
Insert into Player_records value(305,'GJ Maxwell','14-Oct-88','Right_Hand','Right-arm offbreak','Australia',0,NA);
Insert into Player_records value(306,'SPD Smith','2-Jun-89','Right_Hand','Legbreak googly','India',0,NA);
Insert into Player_records value(307,'MN Samuels','5-Feb-81','Right_Hand','Right-arm offbreak','West Indies',0,NA);
Insert into Player_records value(308,'SA Yadav','14-Sep-90','Right_Hand','Right-arm offbreak','India',0,NA);
Insert into Player_records value(309,'KK Cooper','16-Feb-89','Right_Hand','Right-arm medium','West Indies',0,NA);
Insert into Player_records value(310,'JP Faulkner','29-Apr-90','Right_Hand','Left-arm fast-medium','Australia',0,NA);
Insert into Player_records value(311,'HV Patel','23-Nov-90','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(312,'DAJ Bracewell','28-Sep-90','Right_Hand','Right-arm fast-medium','New Zealand',0,NA);
Insert into Player_records value(313,'DJ Harris','31-Dec-79','Right_Hand','Right-arm medium','Australia',0,NA);
Insert into Player_records value(314,'Ankit Sharma','20-Apr-91','Left_Hand','Slow left-arm orthodox','India',0,NA);
Insert into Player_records value(315,'SP Narine','26-May-88','Left_Hand','Right-arm offbreak','West Indies',0,NA);
Insert into Player_records value(316,'GB Hogg','6-Feb-71','Left_Hand','Slow left-arm chinaman','Australia',0,NA);
Insert into Player_records value(317,'RR Bhatkal','1-Sep-85','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(318,'CJ McKay','20-Feb-83','Right_Hand','Right-arm fast-medium','Australia',0,NA);
Insert into Player_records value(319,'N Saini','28-Oct-88','Right_Hand','NULL','India',0,NA);
Insert into Player_records value(320,'DA Miller','10-Jun-89','Left_Hand','Right-arm offbreak','South Africa',0,NA);
Insert into Player_records value(321,'Azhar Mahmood','28-Feb-75','Right_Hand','Right-arm fast-medium','Pakistan',0,NA);
Insert into Player_records value(322,'P Negi','6-Jan-93','Left_Hand','Slow left-arm orthodox','India',0,NA);
Insert into Player_records value(323,'RJ Peterson','4-Aug-79','Left_Hand','Slow left-arm orthodox','South Africa',0,NA);
Insert into Player_records value(324,'KMDN Kulasekara','22-Jul-82','Right_Hand','Right-arm fast-medium','Sri Lanka',0,NA);
Insert into Player_records value(325,'A Ashish Reddy','24-Feb-91','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(326,'V Pratap Singh','3-May-92','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(327,'BB Samantray','14-Dec-88','Right_Hand','NULL','India',0,NA);
Insert into Player_records value(328,'MJ Clarke','2-Apr-81','Right_Hand','Slow left-arm orthodox','Australia',0,NA);
Insert into Player_records value(329,'Gurkeerat Singh','29-Jun-90','Right_Hand','Right-arm offbreak','India',0,NA);
Insert into Player_records value(330,'AP Majumdar','30-Apr-84','Right_Hand','Legbreak googly','India',0,NA);
Insert into Player_records value(331,'PA Reddy','11-Feb-91','Right_Hand','Legbreak','India',0,NA);
Insert into Player_records value(332,'K Upadhyay','18-Jun-86','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(333,'P Awana','19-Jul-86','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(334,'AD Russell','29-Apr-88','Right_Hand','Right-arm fast','West Indies',0,NA);
Insert into Player_records value(335,'A Chandila','5-Dec-83','Right_Hand','Right-arm offbreak','India',0,NA);
Insert into Player_records value(336,'CA Lynn','10-Apr-90','Right_Hand','Slow left-arm orthodox','Australia',0,NA);
Insert into Player_records value(337,'Sunny Gupta','27-Sep-88','Right_Hand','Right-arm offbreak','India',0,NA);
Insert into Player_records value(338,'MC Juneja','12-Sep-90','Right_Hand','Right-arm offbreak','India',0,NA);
Insert into Player_records value(339,'KK Nair','6-Dec-91','Right_Hand','Right-arm offbreak','India',0,NA);
Insert into Player_records value(340,'GH Vihari','13-Oct-93','Right_Hand','Right-arm offbreak','India',0,NA);
Insert into Player_records value(341,'MDKJ Perera','17-Aug-90','Left_Hand','NULL','Sri Lanka',0,NA);
Insert into Player_records value(342,'R Shukla','28-Aug-90','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(343,'B Laughlin','3-Oct-82','Right_Hand','Right-arm fast-medium','Australia',0,NA);
Insert into Player_records value(344,'AS Rajpoot','4-Dec-93','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(345,'M Vohra','18-Jul-93','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(346,'JD Unadkat','18-Oct-91','Right_Hand','Left-arm medium','India',0,NA);
Insert into Player_records value(347,'Mohammed Shami','3-Sep-90','Right_Hand','Right-arm fast-medium','India',0,NA);
Insert into Player_records value(348,'BMAJ Mendis','15-Jan-83','Left_Hand','Legbreak','Sri Lanka',0,NA);
Insert into Player_records value(349,'R Rampaul','15-Oct-84','Left_Hand','Right-arm fast-medium','West Indies',0,NA);
Insert into Player_records value(350,'CH Morris','30-Apr-87','Right_Hand','Right-arm fast-medium','South Africa',0,NA);
Insert into Player_records value(351,'SV Samson','11-Nov-94','Right_Hand','NULL','India',0,NA);
Insert into Player_records value(352,'SMSM Senanayake','9-Feb-85','Right_Hand','Right-arm offbreak','Sri Lanka',0,NA);
Insert into Player_records value(353,'BJ Rohrer','26-Mar-81','Left_Hand','NULL','Australia',0,NA);
Insert into Player_records value(354,'KL Rahul','18-Apr-92','Right_Hand','NULL','India',0,NA);
Insert into Player_records value(355,'Q de Kock','17-Dec-92','Left_Hand','NULL','South Africa',0,NA);
Insert into Player_records value(356,'R Dhawan','19-Feb-90','Right_Hand','Right-arm medium-fast','India',0,NA);
Insert into Player_records value(357,'MG Johnson','2-Nov-81','Left_Hand','Left-arm fast','Australia',0,NA);
Insert into Player_records value(358,'LJ Wright','7-Mar-85','Right_Hand','Right-arm medium-fast','England',0,NA);
Insert into Player_records value(359,'IC Pandey','15-Aug-89','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(360,'CM Gautam','8-Mar-86','Right_Hand','NULL','India',0,NA);
Insert into Player_records value(361,'X Thalaivan Sargunam','15-May-85','Right_Hand','Right-arm offbreak','India',0,NA);
Insert into Player_records value(362,'DJG Sammy','20-Dec-83','Right_Hand','Right-arm medium-fast','West Indies',0,NA);
Insert into Player_records value(363,'KW Richardson','12-Feb-91','Right_Hand','Right-arm fast-medium','Australia',0,NA);
Insert into Player_records value(364,'MM Sharma','18-Sep-88','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(365,'UA Birla','17-Nov-89','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(366,'Parvez Rasool','13-Feb-89','Right_Hand','Right-arm offbreak','India',0,NA);
Insert into Player_records value(367,'Sandeep Sharma','18-May-93','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(368,'S Kaul','19-May-90','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(369,'Sachin Baby','18-Dec-88','Left_Hand','Right-arm offbreak','India',0,NA);
Insert into Player_records value(370,'PV Tambe','8-Oct-71','Right_Hand','Legbreak','India',0,NA);
Insert into Player_records value(371,'NM Coulter-Nile','11-Oct-87','Right_Hand','Right-arm fast','Australia',0,NA);
Insert into Player_records value(372,'CJ Anderson','13-Dec-90','Left_Hand','Left-arm medium-fast','New Zealand',0,NA);
Insert into Player_records value(373,'NJ Maddinson','21-Dec-91','Left_Hand','Slow left-arm orthodox','Australia',0,NA);
Insert into Player_records value(374,'AR Patel','20-Jan-94','Left_Hand','Slow left-arm orthodox','India',0,NA);
Insert into Player_records value(375,'JJ Bumrah','6-Dec-93','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(376,'JDS Neesham','17-Sep-90','Left_Hand','Right-arm medium','New Zealand',0,NA);
Insert into Player_records value(377,'TG Southee','11-Dec-88','Right_Hand','Right-arm medium-fast','New Zealand',0,NA);
Insert into Player_records value(378,'MA Starc','30-Jan-90','Left_Hand','Left-arm fast','Australia',0,NA);
Insert into Player_records value(379,'BR Dunk','11-Mar-87','Left_Hand','NULL','Australia',0,NA);
Insert into Player_records value(380,'RR Rossouw','9-Oct-89','Left_Hand','Right-arm offbreak','South Africa',0,NA);
Insert into Player_records value(381,'Shivam Sharma','9-Sep-93','Right_Hand','Right-arm offbreak','India',0,NA);
Insert into Player_records value(382,'YS Chahal','23-Jul-90','Right_Hand','Legbreak googly','India',0,NA);
Insert into Player_records value(383,'LMP Simmons','25-Jan-85','Right_Hand','Right-arm medium-fast','West Indies',0,NA);
Insert into Player_records value(384,'VH Zol','23-Nov-94','Left_Hand','Right-arm offbreak','India',0,NA);
Insert into Player_records value(385,'BCJ Cutting','30-Jan-87','Right_Hand','Right-arm fast-medium','Australia',0,NA);
Insert into Player_records value(386,'Imran Tahir','27-Mar-79','Right_Hand','Legbreak googly','India',0,NA);
Insert into Player_records value(387,'BE Hendricks','8-Jun-90','Left_Hand','Left-arm fast-medium','South Africa',0,NA);
Insert into Player_records value(388,'S Gopal','4-Sep-93','Right_Hand','Legbreak','India',0,NA);
Insert into Player_records value(389,'M de Lange','13-Oct-90','Right_Hand','Right-arm fast','South Africa',0,NA);
Insert into Player_records value(390,'R Tewatia','20-May-93','Left_Hand','Legbreak','India',0,NA);
Insert into Player_records value(391,'JO Holder','5-Nov-91','Right_Hand','Right-arm medium-fast','West Indies',0,NA);
Insert into Player_records value(392,'Karanveer Singh','8-Nov-87','Right_Hand','Legbreak googly','India',0,NA);
Insert into Player_records value(393,'SS Iyer','6-Dec-94','Right_Hand','Legbreak googly','India',0,NA);
Insert into Player_records value(394,'DJ Hooda','19-Apr-95','Right_Hand','Right-arm offbreak','India',0,NA);
Insert into Player_records value(395,'Anureet Singh','2-Mar-88','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(396,'KS Williamson','8-Aug-90','Right_Hand','Right-arm offbreak','New Zealand',0,NA);
Insert into Player_records value(397,'SA Abbott','29-Feb-92','Right_Hand','Right-arm fast-medium','New Zealand',0,NA);
Insert into Player_records value(398,'J Suchith','16-Jan-94','Left_Hand','Slow left-arm orthodox','India',0,NA);
Insert into Player_records value(399,'RG More','2-Feb-92','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(400,'HH Pandya','11-Oct-93','Right_Hand','Right-arm medium-fast','India',0,NA);
Insert into Player_records value(401,'D Wiese','18-May-85','Right_Hand','Right-arm medium-fast','South Africa',0,NA);
Insert into Player_records value(402,'SN Khan','27-Oct-97','Right_Hand','Legbreak','India',0,NA);
Insert into Player_records value(403,'MJ McClenaghan','11-Jun-86','Left_Hand','Left-arm fast-medium','New Zealand',0,NA);
Insert into Player_records value(404,'DJ Muthuswami','9-Mar-81','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(405,'PJ Cummins','8-May-93','Right_Hand','Right-arm fast','Australia',0,NA);
Insert into Player_records value(406,'SN Thakur','16-Oct-91','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(407,'JC Buttler','8-Sep-90','Right_Hand','NULL','England',0,NA);
Insert into Player_records value(408,'CR Brathwaite','18-Jul-88','Right_Hand','Right-arm fast-medium','West Indies',0,NA);
Insert into Player_records value(409,'MP Stoinis','16-Aug-89','Right_Hand','Right-arm medium','Australia',0,NA);
Insert into Player_records value(410,'Ishan Kishan','18-Jul-98','Left_Hand','NULL','India',0,NA);
Insert into Player_records value(411,'C Munro','11-Mar-87','Left_Hand','Right-arm medium-fast','New Zealand',0,NA);
Insert into Player_records value(412,'P Sahu','21-Aug-85','Right_Hand','Legbreak googly','India',0,NA);
Insert into Player_records value(413,'KH Pandya','24-Mar-91','Left_Hand','Slow left-arm orthodox','India',0,NA);
Insert into Player_records value(414,'AD Nath','10-May-93','Right_Hand','Right-arm medium-fast','India',0,NA);
Insert into Player_records value(415,'MJ Guptill','30-Sep-86','Right_Hand','Right-arm offbreak','New Zealand',0,NA);
Insert into Player_records value(416,'KJ Abbott','18-Jun-87','Right_Hand','Right-arm fast-medium','South Africa',0,NA);
Insert into Player_records value(417,'TM Head','29-Dec-93','Left_Hand','Right-arm offbreak','Australia',0,NA);
Insert into Player_records value(418,'M Ashwin','8-Sep-90','Right_Hand','Legbreak googly','India',0,NA);
Insert into Player_records value(419,'NS Naik','9-Nov-94','Right_Hand','NULL','India',0,NA);
Insert into Player_records value(420,'RR Pant','4-Oct-97','Left_Hand','NULL','India',0,NA);
Insert into Player_records value(421,'SW Billings','15-Jun-91','Right_Hand','NULL','England',0,NA);
Insert into Player_records value(422,'KC Cariappa','13-Apr-94','Right_Hand','Legbreak','India',0,NA);
Insert into Player_records value(423,'PSP Handscomb','26-Apr-91','Right_Hand','NULL','Australia',0,NA);
Insert into Player_records value(424,'Swapnil Singh','22-Jan-91','Right_Hand','Slow left-arm orthodox','India',0,NA);
Insert into Player_records value(425,'J Yadav','22-Jan-90','Right_Hand','Right-arm offbreak','India',0,NA);
Insert into Player_records value(426,'UT Khawaja','18-Dec-86','Left_Hand','Right-arm medium','Australia',0,NA);
Insert into Player_records value(427,'HM Amla','31-Mar-83','Right_Hand','Right-arm offbreak','South Africa',0,NA);
Insert into Player_records value(428,'F Behardien','9-Oct-83','Right_Hand','Right-arm fast-medium','South Africa',0,NA);
Insert into Player_records value(429,'BB Sran','10-Dec-92','Left_Hand','Left-arm medium','India',0,NA);
Insert into Player_records value(430,'A Zampa','31-Mar-92','Right_Hand','Legbreak googly','Australia',0,NA);
Insert into Player_records value(431,'N Rana','27-Dec-93','Left_Hand','Right-arm offbreak','India',0,NA);
Insert into Player_records value(432,'S Kaushik','7-Sep-95','Right_Hand','Slow left-arm chinaman','India',0,NA);
Insert into Player_records value(433,'ER Dwivedi','22-Jul-88','Right_Hand','NULL','India',0,NA);
Insert into Player_records value(434,'CJ Jordan','4-Oct-88','Right_Hand','Right-arm fast-medium','England',0,NA);
Insert into Player_records value(435,'P Amarnath','1-Jun-82','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(436,'B Geeves','13-Jun-82','Right_Hand','Right-arm fast-medium','Australia',0,NA);
Insert into Player_records value(437,'Gagandeep Singh','3-Oct-81','Right_Hand','Right-arm medium-fast','India',0,NA);
Insert into Player_records value(438,'A Nel','15-Jul-77','Right_Hand','Right-arm fast-medium','South Africa',0,NA);
Insert into Player_records value(439,'AM Salvi','20-Oct-81','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(440,'RR Bose','27-Feb-79','Right_Hand','Right-arm fast-medium','India',0,NA);
Insert into Player_records value(441,'SS Sarkar','15-Dec-84','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(442,'RA Shaikh','12-Jun-85','Left_Hand','Left-arm medium','India',0,NA);
Insert into Player_records value(443,'C Ganapathy','10-Jun-81','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(444,'MB Parmar','12-Apr-88','Right_Hand','Right-arm offbreak','India',0,NA);
Insert into Player_records value(445,'AA Kazi','29-Sep-89','Left_Hand','Slow left-arm orthodox','India',0,NA);
Insert into Player_records value(446,'Anand Rajan','17-Apr-87','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(447,'P Prasanth','22-May-85','Left_Hand','Slow left-arm orthodox','India',0,NA);
Insert into Player_records value(448,'SS Mundhe','27-Oct-88','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(449,'RW Price','12-Jun-76','Right_Hand','Slow left-arm orthodox','Zimbabwea',0,NA);
Insert into Player_records value(450,'TP Sudhindra','24-Apr-84','Left_Hand','Right-arm fast','India',0,NA);
Insert into Player_records value(451,'BW Hilfenhaus','15-Mar-83','Right_Hand','Right-arm fast-medium','Australia',0,NA);
Insert into Player_records value(452,'S Badree','9-Mar-81','Right_Hand','Legbreak','West Indies',0,NA);
Insert into Player_records value(453,'P Suyal','15-Oct-89','Right_Hand','Left-arm medium','India',0,NA);
Insert into Player_records value(454,'MG Neser','29-Mar-90','Right_Hand','Right-arm medium','Australia',0,NA);
Insert into Player_records value(455,'V Shankar','26-Jan-91','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(456,'K Santokie','20-Dec-84','Left_Hand','Left-arm medium','West Indies',0,NA);
Insert into Player_records value(457,'JW Hastings','4-Nov-85','Right_Hand','Right-arm fast-medium','Australia',0,NA);
Insert into Player_records value(458,'TA Boult','22-Jul-89','Right_Hand','Left-arm fast-medium','New Zealand',0,NA);
Insert into Player_records value(459,'GS Sandhu','14-Jun-93','Left_Hand','Right-arm fast-medium','Australia',0,NA);
Insert into Player_records value(460,'Mustafizur Rahman','6-Sep-95','Left_Hand','Left-arm fast-medium','Bangladesh',0,NA);
Insert into Player_records value(461,'AF Milne','13-Apr-92','Right_Hand','Right-arm fast','New Zealand',0,NA);
Insert into Player_records value(462,'Kuldeep Yadav','14-Dec-94','Left_Hand','Slow left-arm chinaman','India',0,NA);
Insert into Player_records value(463,'T Shamsi','18-Feb-90','Right_Hand','Slow left-arm chinaman','South Africa',0,NA);
Insert into Player_records value(464,'SM Boland','11-Apr-89','Right_Hand','Right-arm fast-medium','Australia',0,NA);
Insert into Player_records value(465,'DL Chahar','7-Aug-92','Right_Hand','Right-arm medium','India',0,NA);
Insert into Player_records value(466,'P Dharmani','27-Sep-74','Right_Hand','NULL','India',0,NA);
Insert into Player_records value(467,'RV Pawar','6-Sep-79','Left_Hand','Slow left-arm orthodox','India',0,NA);
Insert into Player_records value(468,'KH Devdhar','14-Dec-89','Right_Hand','NULL','India',0,NA);
Insert into Player_records value(469,'T Mishra','22-Dec-86','Right_Hand','Right-arm fast-medium','India',0,NA);
Insert into Player_records value(470,'Asad Rauf','NULL','NULL','NULL','Pakistan',1,1);
Insert into Player_records value(471,'MR Benson','NULL','NULL','NULL','England',1,2);
Insert into Player_records value(472,'Aleem Dar','NULL','NULL','NULL','Pakistan',1,3);
Insert into Player_records value(473,'SJ Davis','NULL','NULL','NULL','England',1,4);
Insert into Player_records value(474,'BF Bowden','NULL','NULL','NULL','New Zealand',1,5);
Insert into Player_records value(475,'IL Howell','NULL','NULL','NULL','South Africa',1,6);
Insert into Player_records value(476,'DJ Harper','NULL','NULL','NULL','Australia',1,7);
Insert into Player_records value(477,'RE Koertzen','NULL','NULL','NULL','South Africa',1,8);
Insert into Player_records value(478,'BR Doctrove','NULL','NULL','NULL','West Indies',1,9);
Insert into Player_records value(479,'AV Jayaprakash','NULL','NULL','NULL','India',1,10);
Insert into Player_records value(480,'BG Jerling','NULL','NULL','NULL','South Africa',1,11);
Insert into Player_records value(481,'M Erasmus','NULL','NULL','NULL','South Africa',1,12);
Insert into Player_records value(482,'HDPK Dharmasena','NULL','NULL','NULL','Sri Lanka',1,NA);
Insert into Player_records value(483,'S Asnani','NULL','NULL','NULL','India',1,NA);
Insert into Player_records value(484,'GAV Baxter','NULL','NULL','NULL','New Zealand',1,NA);
Insert into Player_records value(485,'SS Hazare','NULL','NULL','NULL','India',1,NA);
Insert into Player_records value(486,'K Hariharan','NULL','NULL','NULL','India',1,NA);
Insert into Player_records value(487,'SL Shastri','NULL','NULL','NULL','India',1,NA);
Insert into Player_records value(488,'SK Tarapore','NULL','NULL','NULL','India',1,NA);
Insert into Player_records value(489,'S Ravi','NULL','NULL','NULL','India',1,NA);
Insert into Player_records value(490,'SJA Taufel','NULL','NULL','NULL','Australia',1,NA);
Insert into Player_records value(491,'S Das','NULL','NULL','NULL','India',1,NA);
Insert into Player_records value(492,'AM Saheba','NULL','NULL','NULL','India',1,NA);
Insert into Player_records value(493,'PR Reiffel','NULL','NULL','NULL','Australia',1,NA);
Insert into Player_records value(494,'JD Cloete','NULL','NULL','NULL','South Africa',1,NA);
Insert into Player_records value(495,'AK Chaudhary','NULL','NULL','NULL','India',1,NA);
Insert into Player_records value(496,'VA Kulkarni','NULL','NULL','NULL','India',1,NA);
Insert into Player_records value(497,'BNJ Oxenford','NULL','NULL','NULL','Australia',1,NA);
Insert into Player_records value(498,'CK Nandan','NULL','NULL','NULL','India',1,NA);
Insert into Player_records value(499,'C Shamshuddin','NULL','NULL','NULL','India',1,NA);
Insert into Player_records value(500,'NJ Llong','NULL','NULL','NULL','England',1,NA);
Insert into Player_records value(501,'RK Illingworth','NULL','NULL','NULL','England',1,NA);
Insert into Player_records value(502,'RM Deshpande','NULL','NULL','NULL','India',1,NA);
Insert into Player_records value(503,'K Srinath','NULL','NULL','NULL','India',1,NA);
Insert into Player_records value(504,'SD Fry','NULL','NULL','NULL','Australia',1,NA);
Insert into Player_records value(505,'CB Gaffaney','NULL','NULL','NULL','New Zealand',1,NA);
Insert into Player_records value(506,'PG Pathak','NULL','NULL','NULL','India',1,NA);
Insert into Player_records value(507,'Nitin Menon','NULL','NULL','NULL','India',1,NA);
Insert into Player_records value(508,'K Bharatan','NULL','NULL','NULL','India',1,NA);
Insert into Player_records value(509,'AY Dandekar','NULL','NULL','NULL','India',1,NA);
Insert into Player_records value(510,'KN Ananthapadmanabhan','NULL','NULL','NULL','India',1,NA);
Insert into Player_records value(511,'A Nand Kishore','NULL','NULL','NULL','India',1,NA);
Insert into Player_records value(512,'GA Pratapkumar','NULL','NULL','NULL','India',1,NA);
Insert into Player_records value(513,'RB Tiffin','NULL','NULL','NULL','Zimbabwea',1,NA);
Insert into Player_records value(514,'I Shivram','NULL','NULL','NULL','India',1,NA);
Insert into Player_records value(515,'SD Ranade','NULL','NULL','NULL','India',1,NA);
Insert into Player_records value(516,'TH Wijewardene','NULL','NULL','NULL','Sri Lanka',1,NA);
Insert into Player_records value(517,'AL Hill','NULL','NULL','NULL','New Zealand',1,NA);
Insert into Player_records value(518,'RJ Tucker','NULL','NULL','NULL','Australia',1,NA);
Insert into Player_records value(519,'Subroto Das','NULL','NULL','NULL','India',1,NA);
Insert into Player_records value(520,'K Srinivasan','NULL','NULL','NULL','India',1,NA);
Insert into Player_records value(521,'VK Sharma','NULL','NULL','NULL','India',1,NA);
Insert into Player_records value(523,'AV Wankhade','14-Mar-92','Right_Hand','NULL','India',0,NA);
Insert into Player_records value(524,'B Aparajith','8-Jul-94','Right_Hand','Right-arm offbreak','India',0,NA);
