Insert into Team_records value(1,'Kolkata Knight Riders','KKR');
Insert into Team_records value(2,'Royal Challengers Bangalore','RCB');
Insert into Team_records value(3,'Chennai Super Kings','CSK');
Insert into Team_records value(4,'Kings XI Punjab','KXIP');
Insert into Team_records value(5,'Rajasthan Royals','RR');
Insert into Team_records value(6,'Delhi Daredevils','DD');
Insert into Team_records value(7,'Mumbai Indians','MI');
Insert into Team_records value(8,'Deccan Chargers','DC');
Insert into Team_records value(9,'Kochi Tuskers Kerala','KTK');
Insert into Team_records value(10,'Pune Warriors','PW');
Insert into Team_records value(11,'Sunrisers Hyderabad','SRH');
Insert into Team_records value(12,'Rising Pune Supergiants','RPS');
Insert into Team_records value(13,'Gujarat Lions','GL');
