Insert into Team_records values(1,'Kolkata Knight Riders','KKR');
Insert into Team_records values(2,'Royal Challengers Bangalore','RCB');
Insert into Team_records values(3,'Chennai Super Kings','CSK');
Insert into Team_records values(4,'Kings XI Punjab','KXIP');
Insert into Team_records values(5,'Rajasthan Royals','RR');
Insert into Team_records values(6,'Delhi Daredevils','DD');
Insert into Team_records values(7,'Mumbai Indians','MI');
Insert into Team_records values(8,'Deccan Chargers','DC');
Insert into Team_records values(9,'Kochi Tuskers Kerala','KTK');
Insert into Team_records values(10,'Pune Warriors','PW');
Insert into Team_records values(11,'Sunrisers Hyderabad','SRH');
Insert into Team_records values(12,'Rising Pune Supergiants','RPS');
Insert into Team_records values(13,'Gujarat Lions','GL');
